openapi: 3.0.1
info:
  version: 0.0.1
  title: Sample
paths:
  "/hello":
    get:
      operationId: fetchGreetings
      parameters:
        - $ref: "#/components/parameters/limit"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: KO
          content:
            application/json:
              schema:
                type: string
components:
  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        $ref: "#/components/schemas/Limit"
  schemas:
    Limit:
      type: integer
      format: int32
      maximum: 20
      minimum: 1
      default: 10
